### ISSUE TITLE
does not yet work on windows natively

### ISSUE THREAD

**Issue by chazmcgarvey** [chazmcgarvey/p5-Alien-ZMQ#1]
This module won't be useful until it works on more platforms, including MSWin32.  It should work on Unix-like systems, including cygwin, but MSWin32 support requires a little bit of extra consideration, of course.  I need to find answers to at least these questions:
- What is the difference between ActivePerl and Strawberry Perl?
- Both environments seem to include gcc; can libzmq be built in either or both? How?
- Can libzmq be installed using a binary package? What about runtime differences?
- In the absence of `pkg-config`, how can libzmq be found?

Other issues:
- Mingw32 can build libzmq, but the configure script needs a bourne shell, and dmake might not be cutting it.
- The patch.exe from Strawberry seems to choke on simple patch files.

**Comment by robinsmidsrod** [comment]
This is my result of trying to build on Strawberry Perl 5.16.0:

```
C:\Users\robin>cpan Alien::ZMQ
CPAN: CPAN::SQLite loaded ok (v0.202)
Database was generated on Tue, 04 Jun 2013 09:15:42 GMT
Running install for module 'Alien::ZMQ'
Running make for C/CC/CCM/Alien-ZMQ-0.05.tar.gz
CPAN: Digest::SHA loaded ok (v5.71)
CPAN: Compress::Zlib loaded ok (v2.052)
Checksum for C:\Programs\strawberry-perl\cpan\sources\authors\id\C\CC\CCM\Alien-ZMQ-0.05.tar.gz ok
CPAN: Archive::Tar loaded ok (v1.84)
CPAN: File::Temp loaded ok (v0.22)
CPAN: Parse::CPAN::Meta loaded ok (v1.4404)
CPAN: CPAN::Meta loaded ok (v2.120921)
CPAN: Module::CoreList loaded ok (v2.66)
CPAN: Time::HiRes loaded ok (v1.9725)

  CPAN.pm: Building C/CC/CCM/Alien-ZMQ-0.05.tar.gz

CPAN: CPAN::Reporter loaded ok (v1.2006)
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Alien-ZMQ' version '0.05'
(C:\programs\strawberry-perl\perl\bin\perl.exe Build.PL  exited with 0)
CPAN::Reporter: Build.PL result is 'pass', No errors.
Building Alien-ZMQ
Probing...
'pkg-config' is not recognized as an internal or external command,
operable program or batch file.
'pkg-config' is not recognized as an internal or external command,
operable program or batch file.
gcc -c -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE  -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL
_IMPLICIT_SYS -fno-strict-aliasing -mms-bitfields -s -O2 -I"C:\Programs\strawberry-perl\perl\lib\COR
E" -I"C:\Programs\strawberry-perl\c\include" -o "test-12140.o" "test-12140.c"
test-12140.c:2:17: fatal error: zmq.h: No such file or directory
compilation terminated.
╪MQ not found; building from source...
Downloading ╪MQ 3.2.3 source archive from download.zeromq.org...
Verifying...
Extracting...
Patching...
patching file src/err.hpp

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertation failed!

Program: C:\programs\strawberry-perl\c\bin\patch.EXE
File: .\src\patch\2.5.9\patch-2.5.9-src\patch.c, Line 354

Expression: hunk
Failed to patch ╪MQ at inc/My/Build.pm line 186.
(C:\programs\strawberry-perl\perl\bin\perl.exe ./Build exited with 512)
CPAN::Reporter: Build result is 'unknown', Stopped with an error.
CPAN::Reporter: preparing a CPAN Testers report for Alien-ZMQ-0.05

CPAN::Reporter: this appears to be a duplicate report for the make phase:
UNKNOWN Alien-ZMQ-0.05 MSWin32-x64-multi-thread 4.0

Test report will not be sent.

  CCM/Alien-ZMQ-0.05.tar.gz
  C:\programs\strawberry-perl\perl\bin\perl.exe ./Build -- NOT OK
CPAN: YAML::XS loaded ok (v0.38)
Running Build test
  Can't test without successful make
Running Build install
  Make had returned bad status, install seems impossible
Stopping: 'install' failed for 'Alien::ZMQ'.

C:\Users\robin>
```

This is blocking https://github.com/lestrrat/p5-ZMQ/pull/38

**Comment by chazmcgarvey** [comment]
A number of factors are combining to make MSWin32 support rather difficult:
- Strawberry Perl's patch.exe apparently crashes on diffs which do not have DOS line endings.
- Strawberry Perl is missing some tools (e.g. sh.exe) that are needed to build zeromq with a GCC toolchain.
- Upstream (i.e. zeromq) doesn't support building zeromq with MinGW anyway.  It happens to work for me cross-compiling for i686-mingw32 on x86_64-pc-linux-gnu, and I have _almost_ got it working in an MSYS shell on an actual win32 machine, but there are a lot of hurdles down this path, and I never did get it completely working.
- The supported method to build zeromq is using the packaged sln file; supposedly this can be automated by using MSBuild.exe, but I was never able to get this to work due to missing VS components.

The most realistic thing to do is probably to forget about building from source on Windows and instead download and install some binaries.  Upstream links to some win32 and win64 _installers_ which install zeromq binaries, but they are msvc DLLs and I'm not sure if they are compatible.  ZeroMQ exports a C interface, so I suppose they'll probably work (are these what people currently use with the perl ZMQ bindings?).  Another issue is the fact that they're installers instead of simple packages, so it may not be possible to use them in a completely unautomated way without repackaging.  I do dislike interactive installations...

Anyway, I'll look into this some more soon, and suggestions or patches are always welcome.

**Comment by robinsmidsrod** [comment]
Most typical Windows installers can be run in unattended mode, you can usually find out what it supports by using -? or /? command line parameter. I can't seem to find the links to the v3 MSI files, though. As they use MSI, this information might be of use: http://technet.microsoft.com/en-us/library/cc759262%28v=WS.10%29.aspx

**Comment by chazmcgarvey** [comment]
Have you actually gotten lestrrat's bindings to work on Windows?  If so, which libzmq distribution?  I'm trying the miru.hk libzmq binaries from [this page](http://www.zeromq.org/distro:microsoft-windows) without success.  I think it's not linking with libzmq, presumably because libzmq was built with msvc and the ZMQ::LibZMQ3 installer is using the gcc that comes with Strawberry Perl.  Preliminary code in the mswin32 branch.

**Comment by robinsmidsrod** [comment]
@chazmcgarvey I haven't tried those installers on Windows yet, and no, I haven't gotten zmq to work there yet. I'll see if I can find some time soon to test things out. I really want to make it work.

**Comment by zmughal** [comment]
@robinsmidsrod, if you still need this, could you give https://github.com/chazmcgarvey/p5-Alien-ZMQ/pull/5 a try (if you have the tuits).

**Comment by robinsmidsrod** [comment]
@zmughal I haven't had time to devote to this in ages, so I'm not sure what the current status is. In fact,I'm unsure if I actually have Strawberry Perl installed on my main Win32 machine anymore. I'll see if I find time to test #5, but don't hold your breath.

**Comment by iynehz** [comment]
Hi gents, I just added a comment https://github.com/chazmcgarvey/p5-Alien-ZMQ/pull/5#issuecomment-271135851
